const q=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]));
async function load(path){const r=await fetch(path);if(!r.ok)throw new Error(path);return r.json()}
function badge(s){const label={validated:'Validé','draft-reviewed':'Audité · brouillon',planned:'À construire'}[s]||s;return `<span class="badge ${esc(s)}">${esc(label)}</span>`}
(async()=>{try{const [chapters,series,sources,syntax,build]=await Promise.all([load('data/chapters.json'),load('data/series.json'),load('data/sources.json'),load('data/syntax-registry.json'),load('data/build.json')]);
 const validated=chapters.filter(x=>x.status==='validated').length;const reviewed=chapters.filter(x=>x.status==='draft-reviewed').length;
 q('#stats').innerHTML=[['Chapitres',chapters.length],['Validés',validated],['Audités en brouillon',reviewed],['Séries / TP',series.length]].map(([l,n])=>`<div class="stat"><strong>${n}</strong><span>${l}</span></div>`).join('');
 q('#chaptersGrid').innerHTML=chapters.sort((a,b)=>a.order-b.order).map(c=>`<article class="card"><div class="card-top"><span class="order">CHAPITRE ${c.order}</span>${badge(c.status)}</div><h3>${esc(c.title)}</h3><p>${esc(c.summary)}</p><div class="meta">${c.pages?`${c.pages} pages · `:''}${esc(c.canva_design_id||'')}</div><div class="links">${c.course_url?`<a href="${esc(c.course_url)}">Cours complet</a>`:''}${c.view_url?`<a href="${esc(c.view_url)}" target="_blank" rel="noopener">Voir Canva</a>`:''}${c.edit_url?`<a href="${esc(c.edit_url)}" target="_blank" rel="noopener">Modifier</a>`:''}</div></article>`).join('');
 q('#seriesGrid').innerHTML=series.map(s=>`<article class="card"><div class="card-top"><span class="order">${esc(s.chapter.toUpperCase())}</span>${badge(s.status)}</div><h3>${esc(s.title)}</h3><p>${esc(s.method)}</p><div class="meta">Support validé · version élève et corrigé enseignant conservés dans le dépôt pédagogique.</div></article>`).join('');
 const groups=[['Types SQL',syntax.sql.types],['Contraintes',syntax.sql.constraints],['Manipulation',syntax.sql.dml],['Interrogation',syntax.sql.select],['Fonctions date',syntax.sql.date_functions],['Agrégats',syntax.sql.aggregates]];
 q('#syntaxGrid').innerHTML=groups.map(([t,a])=>`<article class="syntax-card"><h3>${esc(t)}</h3><div class="chips">${a.map(x=>`<span class="chip">${esc(x)}</span>`).join('')}</div></article>`).join('')+`<article class="syntax-card"><h3>Sous-requêtes</h3><p>Non corrélées · uniquement dans <code>WHERE</code>.</p></article><article class="syntax-card"><h3>Jointures</h3><p><code>FROM table1, table2</code> puis égalités PK/FK dans <code>WHERE</code>.</p></article><article class="syntax-card"><h3>MySQL pratique</h3><div class="chips"><span class="chip">AUTO_INCREMENT</span></div></article>`;
 q('#sourcesList').innerHTML=sources.map(s=>`<article class="source-item"><span class="proof">${esc(s.level)}</span><div><strong>${esc(s.title)}</strong><div class="meta">${esc(s.authority)} · ${esc(s.role)}</div></div><a href="${esc(s.url)}" target="_blank" rel="noopener">Source officielle ↗</a></article>`).join('');
 const d=new Date(build.built_at);q('#buildDate').textContent=`Révision ${esc(build.revision)} · ${d.toLocaleDateString('fr-FR')}`;
 }catch(e){console.error(e);document.body.insertAdjacentHTML('beforeend','<div style="padding:20px;background:#fee;color:#900">Erreur de chargement des registres du référentiel.</div>')}})();
q('#menuBtn').addEventListener('click',()=>q('#nav').classList.toggle('open'));document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>q('#nav').classList.remove('open')));
